/**
 * Python 脚本模版
 */
module.exports = {
  description: "Python 脚本骨架 (argparse + logging)",
  category: "python",
  params: {
    name: "脚本描述",
  },
  generate: function (params) {
    var desc = params.name || "Python script";
    return [
      "#!/usr/bin/env python3",
      '"""' + desc + '"""',
      "",
      "import argparse",
      "import logging",
      "import sys",
      "from pathlib import Path",
      "",
      "# ---------- 日志 ----------",
      "logging.basicConfig(",
      '    level=logging.INFO,',
      '    format="%(asctime)s [%(levelname)s] %(message)s",',
      '    datefmt="%Y-%m-%d %H:%M:%S",',
      ")",
      "logger = logging.getLogger(__name__)",
      "",
      "",
      "def main() -> None:",
      '    parser = argparse.ArgumentParser(description="' + desc + '")',
      '    parser.add_argument("--verbose", "-v", action="store_true", help="详细输出")',
      '    parser.add_argument("input", nargs="?", help="输入文件路径")',
      "    args = parser.parse_args()",
      "",
      "    if args.verbose:",
      "        logging.getLogger().setLevel(logging.DEBUG)",
      "",
      '    logger.info("Starting...")',
      "",
      "    try:",
      "        # TODO: 主逻辑",
      "        if args.input:",
      "            path = Path(args.input)",
      "            if not path.exists():",
      '                logger.error(f"File not found: {args.input}")',
      "                sys.exit(1)",
      '            logger.info(f"Processing: {path}")',
      "",
      '        logger.info("Done.")',
      "",
      "    except KeyboardInterrupt:",
      '        logger.info("Interrupted by user")',
      "        sys.exit(130)",
      "    except Exception as e:",
      '        logger.exception(f"Fatal error: {e}")',
      "        sys.exit(1)",
      "",
      "",
      'if __name__ == "__main__":',
      "    main()",
    ].join("\n");
  },
};
